#!/bin/bash
#PBS -l nodes=1:ppn=24
#PBS -l walltime=720:00:00
#PBS -q long
#PBS -o stdout.busco 
#PBS -e stderr.busco
#PBS -k oe
#PBS -m ae
#PBS -M u21465186@tuks.co.za

cd $PBS_O_WORKDIR

module load busco-5.7.1

busco \
 -i /nlustre/users/jsingh/ficus_craterostoma/racon_hifiasm/racon_polish3.fasta \
 -l /nlustre/users/jsingh/ficus_craterostoma/busco_downloads/lineages/embryophyta_odb10 \
 -o busco_hifiasm \
 -m genome \
 -c 24 \
 --offline
