#!/bin/bash
#PBS -l nodes=1:ppn=24
#PBS -l walltime=30:00:00
#PBS -q normal
#PBS -o stdout.minimap2_racon
#PBS -e stderr.minimap2_racon
#PBS -k oe
#PBS -m ae
#PBS -M u21465186@tuks.co.za

cd $PBS_O_WORKDIR

module load minimap2

mkdir minimap2_racon

minimap2 -ax map-ont -t 24 \
        "/nlustre/users/jsingh/ficus_craterostoma/racon_hifiasm/racon_polish3.fasta" \
        "/nlustre/users/jsingh/ficus_craterostoma/raw_reads/jihan-fig1.fq.gz" \
        > /nlustre/users/jsingh/ficus_craterostoma/minimap2_racon/minimap2_racon.sam
