#!/bin/bash
#PBS -l nodes=1:ppn=24
#PBS -l walltime=720:00:00
#PBS -q bigmem
#PBS -o stdout.canu
#PBS -e stderr.canu
#PBS -k oe
#PBS -m ae
#PBS -M u21465186@tuks.co.za

cd $PBS_O_WORKDIR

module load canu

canu -p ficus_craterostoma_canu_assembly \
 -d canu_out \
 genomeSize=560m \
 useGrid=false \
 -nanopore-corrected /nlustre/users/jsingh/ficus_craterostoma/nanofilt_out/fc_trim.fq maxThreads=24 maxMemory=750
 
