#!/bin/bash
#PBS -l nodes=1:ppn=24
#PBS -l walltime=8:00:00
#PBS -q normal
#PBS -o stdout.nanofilt
#PBS -e stderr.nanofilt
#PBS -k oe
#PBS -m ae
#PBS -M u21465186@tuks.co.za

cd $PBS_O_WORKDIR

mkdir nanofilt_out

module load nanofilt

NanoFilt --length 1000 < /nlustre/users/jsingh/ficus_salicifolia/chopper_q10/salicifolia_q10_trim.fq > /nlustre/users/jsingh/ficus_salicifolia/nanofilt_out/salicifolia.fq
