#!/bin/bash
#PBS -l nodes=1:ppn=24
#PBS -l walltime=720:00:00
#PBS -q bigmem
#PBS -o stdout.racon_flye
#PBS -e stderr.racon_flye
#PBS -k oe
#PBS -m ae
#PBS -M u21465186@tuks.co.za

cd $PBS_O_WORKDIR

module load racon

cd $PBS_O_WORKDIR

racon -m 3 -x -5 -g -4 -w 500 -t 24 \
/nlustre/users/jsingh/ficus_craterostoma/raw_reads/jihan-fig1.fq \
/nlustre/users/jsingh/ficus_craterostoma/minimap2_shasta_out/ficus_craterostoma_shasta.sam \
/nlustre/users/jsingh/ficus_craterostoma/shasta_out/Assembly.fasta \
> racon_shasta/racon_polish1.fasta

